/* LOADING ACTIONS */
export const APP_LOADING = 'APP_LOADING';

/* AUTH ACTIONS */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
